import { DSH_COMPATIBILITY, DSH_VERSION, isDshVersionCompatible } from './version.js'
import { PEER_HOST_ERROR_CODES } from './peer-host.js'

export const CODINGNS_DSH_ERROR_CODES = {
  PLUGIN_MANIFEST_INVALID: 'PLUGIN_MANIFEST_INVALID',
  DSH_VERSION_UNSUPPORTED: 'DSH_VERSION_UNSUPPORTED',
  HOST_ENTRY_UNAVAILABLE: 'HOST_ENTRY_UNAVAILABLE',
  CLIENT_ENTRY_UNAVAILABLE: 'CLIENT_ENTRY_UNAVAILABLE',
  TRANSPORT_NOT_READY: 'TRANSPORT_NOT_READY',
  PEER_HOST_NOT_FOUND: 'PEER_HOST_NOT_FOUND',
  PEER_HOST_VERSION_MISMATCH: 'PEER_HOST_VERSION_MISMATCH',
  PEER_HOST_SESSION_REQUIRED: 'PEER_HOST_SESSION_REQUIRED',
  DEBUG_INVALID_REQUEST: 'DEBUG_INVALID_REQUEST',
  DEBUG_WORKSPACE_REQUIRED: 'DEBUG_WORKSPACE_REQUIRED',
  DEBUG_WORKSPACE_SESSION_MISMATCH: 'DEBUG_WORKSPACE_SESSION_MISMATCH',
  DEBUG_GENERATION_STALE: 'DEBUG_GENERATION_STALE',
  DEBUG_REVISION_CONFLICT: 'DEBUG_REVISION_CONFLICT',
  DEBUG_PROFILE_NOT_FOUND: 'DEBUG_PROFILE_NOT_FOUND',
  DEBUG_PROCESS_INSTANCE_NOT_FOUND: 'DEBUG_PROCESS_INSTANCE_NOT_FOUND',
  DEBUG_PROCESS_IDENTITY_MISMATCH: 'DEBUG_PROCESS_IDENTITY_MISMATCH',
  DEBUG_PORT_LEASE_CONFLICT: 'DEBUG_PORT_LEASE_CONFLICT',
  DEBUG_RUNTIME_NOT_FOUND: 'DEBUG_RUNTIME_NOT_FOUND',
  DEBUG_PROXY_ROUTE_NOT_FOUND: 'DEBUG_PROXY_ROUTE_NOT_FOUND',
  DEBUG_DSH_HOST_API_UNAVAILABLE: 'DEBUG_DSH_HOST_API_UNAVAILABLE',
  PEER_HOST_NOT_READY: PEER_HOST_ERROR_CODES.NOT_READY,
  PEER_HOST_PROXY_PATH_NOT_ALLOWED: PEER_HOST_ERROR_CODES.PROXY_PATH_NOT_ALLOWED,
  PEER_HOST_PROXY_ACCESS_DENIED: PEER_HOST_ERROR_CODES.PROXY_ACCESS_DENIED,
  PEER_HOST_SCOPE_MISMATCH: PEER_HOST_ERROR_CODES.SCOPE_MISMATCH,
  PEER_HOST_PROXY_UNREACHABLE: PEER_HOST_ERROR_CODES.PROXY_UNREACHABLE,
  PEER_HOST_RESPONSE_INVALID: PEER_HOST_ERROR_CODES.RESPONSE_INVALID,
  PEER_HOST_TOOL_UNSUPPORTED: PEER_HOST_ERROR_CODES.TOOL_UNSUPPORTED,
  PEER_HOST_INVALID_ROUTE: PEER_HOST_ERROR_CODES.INVALID_ROUTE,
  PEER_HOST_DUPLICATE: PEER_HOST_ERROR_CODES.DUPLICATE,
  PEER_HOST_PLUGIN_MISSING: PEER_HOST_ERROR_CODES.PLUGIN_MISSING,
  PEER_HOST_IDENTITY_CHANGED: PEER_HOST_ERROR_CODES.IDENTITY_CHANGED,
  PEER_HOST_UNREACHABLE: PEER_HOST_ERROR_CODES.UNREACHABLE,
  PEER_HOST_RELAY_UNAVAILABLE: PEER_HOST_ERROR_CODES.RELAY_UNAVAILABLE,
  PEER_HOST_AGGREGATE_UNAVAILABLE: PEER_HOST_ERROR_CODES.AGGREGATE_UNAVAILABLE,
  PEER_HOST_STALE_GENERATION: PEER_HOST_ERROR_CODES.STALE_GENERATION,
} as const

export const SUPPORTED_DSH_VERSION = DSH_VERSION
export const SUPPORTED_DSH_COMPATIBILITY = DSH_COMPATIBILITY

export type CodingNsDshErrorCode = typeof CODINGNS_DSH_ERROR_CODES[keyof typeof CODINGNS_DSH_ERROR_CODES]

/** 统一错误形状；阶段 0 只定义，不主动产生这些业务错误。 */
export class CodingNsDshError extends Error {
  readonly code: CodingNsDshErrorCode

  constructor(code: CodingNsDshErrorCode, message: string, options?: ErrorOptions) {
    super(message, options)
    this.name = 'CodingNsDshError'
    this.code = code
  }
}

/** 启动期严格检查 DSH 兼容范围，不对未知版本静默降级。 */
export function assertSupportedDshVersion(version: string): void {
  if (!isDshVersionCompatible(version)) {
    throw new CodingNsDshError(
      CODINGNS_DSH_ERROR_CODES.DSH_VERSION_UNSUPPORTED,
      `不支持的 DSH 版本: ${version}；当前插件兼容范围为 ${SUPPORTED_DSH_COMPATIBILITY}`,
    )
  }
}
